enyo.depends(
	"css/Tweaks.css",
	"css/Wosi.css",	
	"source/Tweaks.js",
	"source/Main.js",
	"source/Config.js",
	"source/Help.js",
	"source/Wosi.js",
	"source/Startup.js",
	"source/PreferencesService.js"
);
